
default: &default
      adapter: postgresql
      encoding: unicode
      pool: 5
      username: username1
      password: password
      host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: instapost_development

test:
  <<: *default
  database: instapost_test

production:
  <<: *default
  database: instapost_production
